### PR TITLE
[Merged by Bors] - Implement product image selection

### PR DESCRIPTION
**Pull request by sbernauer**
## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by sbernauer** [comment]
Started https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/22

**Comment by sbernauer** [comment]
Tests passed :partying_face:

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by sbernauer** [comment]
thx!

**Pull request closed without merging**
