### PR TITLE
[Merged by Bors] - Don't run init container as root and avoid chmod and chowning

### LINKED ISSUE #602: init container should not fail with extra directories in data dir
### Affected version

latest

### Current and expected behavior

This is the output of an init container showing the problem

```
copying /stackable/config to /stackable/rwconfig
[/stackable/quorum_tls] Cleaning up truststore - just in case
[/stackable/quorum_tls] Creating truststore
Certificate was added to keystore
[/stackable/quorum_tls] Creating certificate chain
[/stackable/quorum_tls] Creating keystore
[/stackable/quorum_tls] chown and chmod
[/stackable/client_tls] Cleaning up truststore - just in case
[/stackable/client_tls] Creating truststore
Certificate was added to keystore
[/stackable/client_tls] Creating certificate chain
[/stackable/client_tls] Creating keystore
[/stackable/client_tls] chown and chmod
[/stackable/data] chown and chmod
chown: changing ownership of '/stackable/data/.snapshot/6hour.2022-12-01_1215': Read-only file system
chown: changing ownership of '/stackable/data/.snapshot': Read-only file system
```

This is a new PV(C) which is empty. 
But NetApp (in this case, other solutions might do something similar) shows a special `.snapshot` directory which can be used to access old snapshots.

The init container currently tries to chown (and chmod) the provided data directory recursively which fails in this case.

Please note: This ticket is ZooKeeper specific but we need to check our other operators for a similar pattern.

### Possible solution

We need to check whether the `chown` and `chmod` statements are even still needed, they have been around since forcever but our images have improved since then.

Idea only: We might want to think about writing the init container stuff into a bash script which we then execute in the entrypoint. That'd allow us to use `set -x` in the bash script so we get the output of every line printed to screen which helps debugging. But we need to make sure that no sensitive information can be leaked.

### Additional context

_No response_

### Environment

_No response_

### Would you like to work on fixing this bug?

_No response_

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Fixes #602 

## Review Checklist

- [x] Code contains useful comments
- [x] CRD change approved (or not applicable)
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by sbernauer** [comment]
Started test on GKE https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/23

**Comment by sbernauer** [comment]
Tests on GKE and Openshift (thanks to @razvan) passed

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by maltesander** [comment]
bors merge

**Pull request closed without merging**
