### PR TITLE
[Merged by Bors] - Increase timeout for pip installation in test

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Seems like something around here causes the failures. See https://ci.stackable.tech/job/zookeeper-operator-it-nightly/41/consoleFull

Jenkins run: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/11/console

## Review Checklist

- [x] Code contains useful comments
- [x] CRD change approved (or not applicable)
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by adwk67 — COMMENTED** [review]
Is this rendered obsolete if the testing-tools image is used?

**Comment by sbernauer** [comment]
When it will be used: yes

**Comment by sbernauer** [comment]
And you also triggered https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/11/console
Thanks!

**Review by adwk67 — APPROVED** [review]

**Comment by sbernauer** [comment]
Awesome, thanks! Sadly i can't approve my own PR, could you please do so? Feel free to merge as well

**Pull request closed without merging**
