### PR TITLE
Let secret-operator handle PKCS#12 conversion

### PR DESCRIPTION
**Pull request by nightkr**
# Description

Requires https://github.com/stackabletech/secret-operator/pull/286 and https://github.com/stackabletech/operator-rs/pull/610

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by razvan — COMMENTED** [review]
I get this when running the smoke test with tls enabled everywhere:
```
Caused by: java.io.FileNotFoundException: /stackable/server_tls/keystore.p12 (No such file or directory)                                                                                                                       │
│     at java.base/java.io.FileInputStream.open0(Native Method)                                                                                                                                                                  │
│     at java.base/java.io.FileInputStream.open(FileInputStream.java:219)                                                                                                                                                        │
│     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)                                                                                                                                                      │
│     at org.apache.zookeeper.common.StandardTypeFileKeyStoreLoader.loadKeyStore(StandardTypeFileKeyStoreLoader.java:53)                                                                                                         │
│     at org.apache.zookeeper.common.X509Util.loadKeyStore(X509Util.java:410)                                                                                                                                                    │
│     at org.apache.zookeeper.common.X509Util.createKeyManager(X509Util.java:466)                                                                                                                                                │
│     ... 27 common frames omitted                                               
```

**Comment by nightkr** [comment]
Are you sure that 1) you're running a trunk build of secret-op, and 2) that your secret-op is new enough to include the PR?

**Review by razvan — COMMENTED** [review]
Looks much better and the smoke tests pass on OS. I won't approve due to the missing operator-rs version.

**Comment by razvan** [comment]
Ping @nightkr I this can be updated with the latest operator-rs version. I'd quickly review again and approve.

**Comment by nightkr** [comment]
@razvan done in e45ce9165039c4f2a82631f91626f76364a756b6

**Review by razvan — DISMISSED** [review]
lgtm and the tests pass on OS. need to solve that last conflict before merging.

**Review by razvan — APPROVED** [review]

**Comment by sbernauer** [comment]
:partying_face:

**Pull request merged**
