### PR TITLE
configOverrides are now able to overwrite configs written by the operator

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Fixes https://github.com/stackabletech/zookeeper-operator/issues/761

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [x] Code contains useful comments
- [x] (Integration-)Test cases added
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by adwk67 — DISMISSED** [review]
LGTM, although I think a test for this would be good. This operator is a dependency for several other operators and it would be good to know asap when something with the overrides is broken. What do you think? In a separate PR?

**Comment by maltesander** [comment]
> LGTM, although I think a test for this would be good. This operator is a dependency for several other operators and it would be good to know asap when something with the overrides is broken. What do you think? In a separate PR?

+1, i think we have override tests in several other operators

**Comment by sbernauer** [comment]
> +1, i think we have override tests in several other operators

Do you by any chance have a link where these are? Ideally a testcase that overrides what the operator has written

**Comment by maltesander** [comment]
> Do you by any chance have a link where these are? Ideally a testcase that overrides what the operator has written.

I know that we do it for resources in the resources tests at least,  not sure anymore if we test it elsewhere after having a quick look.

**Comment by sbernauer** [comment]
Was not able to find any test so far, so I wrote one. It's not nice, but it was hard and honest work :D

**Review by adwk67 — DISMISSED** [review]
LGTM - thanks for doing this! (I know we are looking at doing more testing in code, but - out of curiosity - would it have been easier to do an integration test for this?)

**Comment by sbernauer** [comment]
It probably would have been easier, yes. But I prefer having a test that passes in ms rather than minutes, so I did take the time :sweat_smile:

**Review by adwk67 — APPROVED** [review]
lgtm.

**Pull request merged**
