### PR TITLE
[Merged by Bors] - Enable Prometheus scraping

### LINKED ISSUE #379: Enable Prometheus scraping
Annotation `prometheus.io/scrape: "true"` should be added to role services

### PR DESCRIPTION
**Pull request by teozkr**
## Description

Fixes #379 

## Review Checklist
- [x] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by lfrancke** [comment]
I know it is boring but could you add a section to the docs for this?
I don't think it needs to be a whole book about monitoring, maybe just a monitoring document for now that mentions that all pods that are created have this label and are prometheus "enabled"?

**Comment by teozkr** [comment]
@lfrancke I created https://github.com/stackabletech/documentation/pull/132 for the docs since this is more of a platform-wide concern. Do you want this to be documented in each individual operator as well?

**Comment by lfrancke** [comment]
I'm torn....let's say someone looks at the ZK Operator docs I think it'd be good to at least have a link to the platform-wide monitoring docs.

**Comment by teozkr** [comment]
Does Antora have a fancy way to link between products in the same playbook, or should I just use the full URL?

**Comment by teozkr** [comment]
Ok, figured out how to do it and added a note both here and in https://github.com/stackabletech/kafka-operator/pull/308.

**Review by lfrancke — APPROVED** [review]

**Pull request closed without merging**
