### PR TITLE
Update Helm CRDs

### PR DESCRIPTION
**Pull request by teozkr**
## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)

### CODE REVIEW

**Review by lfrancke — APPROVED** [review]

**Comment by lfrancke** [comment]
LOL

**Comment by teozkr** [comment]
Fitting.

**Pull request merged**
