### PR TITLE
[Merged by Bors] - Document discovery CM ZOOKEEPER_CLIENT_PORT

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Closes https://github.com/stackabletech/zookeeper-operator/issues/677, leftover of https://github.com/stackabletech/zookeeper-operator/pull/676

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by fhennig** [comment]
Can you add a sentence like "The Operator keeps the port in this Property always in sync with the Port in the ZOOKEEPER connection string. If you want to write your own discovery ConfigMap, provide both properties."

**Comment by sbernauer** [comment]
WDYT of documenting it a global level, e.g. https://github.com/stackabletech/documentation/pull/400?

**Comment by fhennig** [comment]
Yes it's probably better to keep it there, good point

**Review by fhennig — APPROVED** [review]

**Comment by sbernauer** [comment]
bors r+
Thanks!

**Pull request closed without merging**
